
image:
- Visual Studio 2017
- Ubuntu
before_build:
  # Display .NET Core version
  - dotnet --list-sdks
  - dotnet --version
  # Select a version
  - dotnet new globaljson --sdk-version 2.2.103
  # Restore deps
  - dotnet restore
build_script:
  - dotnet build
before_test:
  - bash scripts/restore.sh
test_script:
  - dotnet test tests/LSP.Tests
  - dotnet test tests/ProjectCracker.Tests
  - dotnet test tests/FSharpLanguageServer.Tests